export const OPEN_MODAL = 'OPEN_MODAL'
export const CLOSE_MODAL = 'CLOSE_MODAL'
export const CREATE_NEW_PROJECT = 'CREATE_NEW_PROJECT'
export const PROJECT_NAME = 'PROJECT_NAME'
export const PROJECT_ID = 'PROJECT_ID'
export const SET_TEST = 'SET_TEST'
export const SET_PROJECTS = 'SET_PROJECTS'